requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
    branch: dev
  - https://github.com/pyexcel/pyexcel-mobans
configuration:
  configuration_dir: "pyexcel-mobans:config"
  template_dir:
    - "pyexcel-mobans:templates"
    - "pypi-mobans:templates"
    - ".moban.d"
  configuration: pyexcel.yml
targets:
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/custom_conf.py.jj2"
  - .travis.yml: travis.yml
  - requirements.txt: requirements.txt.jj2
  - min_requirements.txt: minimum_requirements.txt
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: NEW_BSD_LICENSE.jj2
  - MANIFEST.in: CUSTOM_MANIFEST.in.jj2
  - README.rst: README.rst
  - "docs/source/guide.rst": "docs/source/guide.rst"
  - test.sh: test.sh
  - test.bat: test.bat
  - .gitignore: commons-gitignore.jj2
  - "pyexcel/__version__.py": version.txt
  - "docs/source/index.rst": "docs/source/pyexcel-index.rst.jj2"
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
